<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Sentinel\Events;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Foundation\Events\Dispatchable;

/**
 * Event fired when a user enables TOTP authentication.
 *
 * This event is dispatched when a user successfully enables Time-based
 * One-Time Password (TOTP) authentication for their account. TOTP provides
 * two-factor authentication by requiring users to enter time-sensitive codes
 * generated by authenticator apps like Google Authenticator, Authy, or 1Password.
 *
 * Listeners can use this event to log security enhancements, send confirmation
 * emails to the user, generate backup recovery codes, or update security audit
 * trails showing when users strengthen their account protection.
 *
 * @author Brian Faust <brian@cline.sh>
 * @psalm-immutable
 */
final readonly class TotpEnabled
{
    use Dispatchable;

    /**
     * Create a new TOTP enabled event instance.
     *
     * @param Authenticatable $user The authenticated user who enabled TOTP authentication.
     *                              This user's account will now require TOTP codes during
     *                              login, enhancing their security by adding a second factor
     *                              beyond just username and password authentication.
     */
    public function __construct(
        public Authenticatable $user,
    ) {}
}
