<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Sentinel\Events;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Foundation\Events\Dispatchable;

/**
 * Event fired when a user registers a WebAuthn credential.
 *
 * This event is dispatched when a user successfully registers a new WebAuthn
 * credential for passwordless authentication. WebAuthn enables secure, phishing-
 * resistant authentication using hardware security keys (YubiKey, Titan), platform
 * authenticators (Touch ID, Face ID, Windows Hello), or other FIDO2-compliant devices.
 *
 * Listeners can use this event to log security device registrations, send confirmation
 * notifications about the new authentication method, or update security dashboards
 * showing the user's registered authenticators.
 *
 * @author Brian Faust <brian@cline.sh>
 * @psalm-immutable
 */
final readonly class WebAuthnCredentialRegistered
{
    use Dispatchable;

    /**
     * Create a new WebAuthn credential registered event instance.
     *
     * @param Authenticatable $user         The authenticated user who registered the credential.
     *                                      This user can now use the registered WebAuthn device
     *                                      for passwordless authentication or as a second factor.
     * @param string          $credentialId The unique identifier for the registered credential.
     *                                      This ID is generated by the authenticator device and
     *                                      used to identify which credential was used during
     *                                      authentication challenges.
     * @param string          $name         The user-assigned friendly name for the credential.
     *                                      This helps users identify their devices in security
     *                                      settings (e.g., "MacBook Touch ID", "YubiKey 5").
     */
    public function __construct(
        public Authenticatable $user,
        public string $credentialId,
        public string $name,
    ) {}
}
