<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Sentinel\Totp;

use BaconQrCode\Renderer\Image\SvgImageBackEnd;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;

use function base64_encode;
use function rawurlencode;
use function sprintf;

/**
 * Immutable value object representing a TOTP setup session.
 *
 * Encapsulates the data needed to configure TOTP in an authenticator app.
 * Provides QR code generation (as SVG or data URI) and provisioning URIs
 * compatible with standard authenticator applications including Google
 * Authenticator, Authy, Microsoft Authenticator, and 1Password.
 *
 * This object is returned by TotpManager::beginSetup() and should be used
 * to display setup instructions to users during TOTP enrollment.
 *
 * @author Brian Faust <brian@cline.sh>
 * @psalm-immutable
 */
final readonly class TotpSetup
{
    /**
     * Create a new TOTP setup value object.
     *
     * @param string $secret      The base32-encoded TOTP secret key generated by
     *                            TotpVerifier. This is the shared secret that will
     *                            be used to generate time-based one-time passwords.
     * @param string $issuer      The service name displayed in authenticator apps
     *                            (e.g., "MyApp", "Acme Corp"). Helps users identify
     *                            which service the TOTP code is for when they have
     *                            multiple accounts configured.
     * @param string $accountName The account identifier displayed in authenticator
     *                            apps, typically the user's email address or username.
     *                            Used to distinguish between multiple accounts for
     *                            the same service.
     */
    public function __construct(
        private string $secret,
        private string $issuer,
        private string $accountName,
    ) {}

    /**
     * Get the base32-encoded TOTP secret key.
     *
     * This secret can be manually entered into authenticator apps that don't
     * support QR code scanning. Display this to users as a backup method.
     *
     * @return string The TOTP secret in base32 format.
     */
    public function getSecret(): string
    {
        return $this->secret;
    }

    /**
     * Generate the otpauth:// provisioning URI for authenticator apps.
     *
     * Creates a URI following the Key Uri Format specification that
     * authenticator apps use to configure TOTP accounts. The URI encodes
     * the issuer, account name, and secret in a standardized format.
     *
     * Format: otpauth://totp/Issuer:account@example.com?secret=SECRET&issuer=Issuer
     *
     * @see https://github.com/google/google-authenticator/wiki/Key-Uri-Format
     * @return string The provisioning URI suitable for QR code encoding or
     *                manual entry into authenticator applications.
     */
    public function getProvisioningUri(): string
    {
        return sprintf(
            'otpauth://totp/%s:%s?secret=%s&issuer=%s',
            rawurlencode($this->issuer),
            rawurlencode($this->accountName),
            $this->secret,
            rawurlencode($this->issuer),
        );
    }

    /**
     * Generate a QR code as an SVG string for display or download.
     *
     * Creates a 200x200px SVG QR code containing the provisioning URI.
     * SVG format is preferred for web display as it scales without quality
     * loss and can be styled with CSS.
     *
     * @return string Complete SVG markup containing the QR code image.
     */
    public function getQrCodeSvg(): string
    {
        // Configure renderer for 200x200 SVG output
        $renderer = new ImageRenderer(
            new RendererStyle(200),
            new SvgImageBackEnd(),
        );

        $writer = new Writer($renderer);

        return $writer->writeString($this->getProvisioningUri());
    }

    /**
     * Generate a QR code as a data URI for inline HTML embedding.
     *
     * Returns a base64-encoded data URI that can be used directly in an
     * img tag's src attribute without requiring separate file serving.
     *
     * Example usage:
     * ```php
     * <img src="{{ $setup->getQrCodeDataUri() }}" alt="TOTP QR Code" />
     * ```
     *
     * @return string Base64-encoded SVG data URI ready for use in img src
     *                attributes or CSS backgrounds.
     */
    public function getQrCodeDataUri(): string
    {
        $svg = $this->getQrCodeSvg();

        return 'data:image/svg+xml;base64,'.base64_encode($svg);
    }
}
