<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Sentinel\Exceptions;

use RuntimeException;

/**
 * Thrown when WebAuthn assertion verification fails.
 *
 * This exception is thrown when a WebAuthn authentication assertion cannot be
 * verified during the login process. WebAuthn assertions are cryptographic proofs
 * generated by authenticator devices (security keys, biometric sensors) that
 * demonstrate possession of the registered credential without transmitting secrets.
 *
 * Common scenarios that trigger this exception:
 * - Signature verification fails due to incorrect credential
 * - User canceled the authentication prompt on their device
 * - Challenge response doesn't match the expected value
 * - Authenticator data indicates a compromised or cloned device
 * - Credential ID doesn't match any registered credential for the user
 *
 * @author Brian Faust <brian@cline.sh>
 */
final class InvalidWebAuthnAssertionException extends RuntimeException implements SentinelException
{
    /**
     * Create an exception for invalid WebAuthn assertion.
     *
     * @return self A new exception instance with an appropriate error message
     *              explaining that the WebAuthn assertion verification failed.
     */
    public static function invalidAssertion(): self
    {
        return new self('The provided WebAuthn assertion is invalid.');
    }
}
