<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Sentinel\Exceptions;

use RuntimeException;

/**
 * Thrown when TOTP code verification fails.
 *
 * This exception is thrown when a user attempts to authenticate using a
 * Time-based One-Time Password (TOTP) code that fails verification. TOTP
 * codes are 6-digit time-sensitive codes generated by authenticator apps
 * and are valid only for a short time window (typically 30 seconds).
 *
 * Common scenarios that trigger this exception:
 * - User enters an incorrect or mistyped TOTP code
 * - TOTP code has expired (outside the valid time window)
 * - System time is out of sync between server and authenticator device
 * - TOTP secret is corrupted or doesn't match the stored value
 *
 * @author Brian Faust <brian@cline.sh>
 */
final class InvalidTotpCodeException extends RuntimeException implements SentinelException
{
    /**
     * Create an exception for invalid TOTP code.
     *
     * @return self A new exception instance with an appropriate error message
     *              explaining that the TOTP code verification failed.
     */
    public static function invalidCode(): self
    {
        return new self('The provided TOTP code is invalid.');
    }
}
